apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: k8s-workspace
type: Opaque
data:
  #k8s-db-user
  # mongo-username: azhzLWRiLXVzZXI=
  #k8sdbuserpwd
  # mongo-password: azhzZGJ1c2VycHdk
  #admin
  mongo-username: YWRtaW4=
  #password
  mongo-password: cGFzc3dvcmQ=